# Generated by Django 5.2.4 on 2025-08-04 07:50

import detector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Model3D",
        ),
        migrations.AlterModelOptions(
            name="clothingitem",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Clothing Item",
                "verbose_name_plural": "Clothing Items",
            },
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="clothingitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("top", "Top"),
                    ("bottom", "Bottom"),
                    ("dress", "Dress"),
                    ("other", "Other"),
                ],
                default="top",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="clothingitem",
            name="image",
            field=models.ImageField(
                help_text="Upload a clear image of the clothing item",
                upload_to="clothes/",
                validators=[detector.models.validate_image],
            ),
        ),
    ]
