# Generated by Django 5.2.4 on 2025-08-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0002_delete_model3d_alter_clothingitem_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clothingitem",
            name="price",
        ),
        migrations.AlterField(
            model_name="clothingitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("top", "Top"),
                    ("bottom", "Bottom"),
                    ("dress", "Dress"),
                    ("other", "Other"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="clothingitem",
            name="image",
            field=models.ImageField(upload_to="clothing/"),
        ),
    ]
